### PR TITLE
New Comment To Api

### PR DESCRIPTION
**Pull request by srijeet-at-vt**
Now we can add a new comment to post.

### CODE REVIEW

**Comment by jonmahoney15** [comment]
looks like some code is missing?

**Review by jonmahoney15 — CHANGES_REQUESTED** [review]
Update code

**Comment by srijeet-at-vt** [comment]
> looks like some code is missing?

What's wrong? It was working on my end.

**Comment by jonmahoney15** [comment]
After discussion this is good to go, other code is already on main

**Pull request merged**
